import {Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";


const inter = Inter({
  subsets: ["latin"],
  weight : ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-main text-white h-auto ${inter.className} antialiased`}
      >
       <main className="max-w-[1440px] mx-auto flex">
        <div className="w-[241px] ml-auto border-r border-[#111B3C] min-h-screen fixed h-screen">
          <Sidebar/>
        </div>
       <div className="flex-1 ml-[241px]">
         <Header/>
         {children}
       </div>
       </main>
      </body>
    </html>
  );
}
