import { Geist, Geist_Mono , Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight : ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-main text-white ${inter.className} antialiased`}
      >
       <main className="max-w-[1440px] mx-auto flex">
        <div className="w-[241px] border-r border-gray-200 h-screen">
          <Sidebar/>
        </div>
         {children}
       </main>
      </body>
    </html>
  );
}
